/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.Pelanggan;
import db.ConnectionManager;
import exec.ExecutePelanggan;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ALIK
 */
public class UserFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserFrame
     */
    public UserFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInputPelanggan = new javax.swing.JPanel();
        txtNamaPelanggan = new javax.swing.JTextField();
        txtNoTelponPelanggan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAlamatPelanggan = new javax.swing.JTextArea();
        btnSubmitPelanggan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taAlamatPelanggan.setColumns(20);
        taAlamatPelanggan.setRows(5);
        jScrollPane1.setViewportView(taAlamatPelanggan);

        btnSubmitPelanggan.setText("Submit");
        btnSubmitPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitPelangganActionPerformed(evt);
            }
        });

        jLabel1.setText("Nomor Telepon ");

        jLabel2.setText("Nama Pelanggan");

        jLabel3.setText("Alamat");

        javax.swing.GroupLayout pnlInputPelangganLayout = new javax.swing.GroupLayout(pnlInputPelanggan);
        pnlInputPelanggan.setLayout(pnlInputPelangganLayout);
        pnlInputPelangganLayout.setHorizontalGroup(
            pnlInputPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputPelangganLayout.createSequentialGroup()
                .addGroup(pnlInputPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputPelangganLayout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(btnSubmitPelanggan))
                    .addGroup(pnlInputPelangganLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(pnlInputPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(pnlInputPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(txtNoTelponPelanggan)
                                .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        pnlInputPelangganLayout.setVerticalGroup(
            pnlInputPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputPelangganLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNoTelponPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSubmitPelanggan)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInputPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInputPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitPelangganActionPerformed
        // TODO add your handling code here:
        String nama = txtNamaPelanggan.getText();
        String no_telp = txtNoTelponPelanggan.getText();
        String alamat = taAlamatPelanggan.getText();
        Pelanggan p = new Pelanggan(nama, no_telp, alamat);
        ExecutePelanggan ex = new ExecutePelanggan();
        int hasil = ex.insertData(p);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            String query = "select * from pelanggan ORDER BY id_pelanggan DESC LIMIT 1";
            ConnectionManager conMan = new ConnectionManager();
            Connection conn = conMan.logOn();
            try {
                Statement stm = conn.createStatement();
                ResultSet rs = stm.executeQuery(query);
                if(rs.next()){
                    System.out.println(rs.getInt("id_pelanggan"));   
                }
            } catch (SQLException exception) {
                exception.printStackTrace();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
    }//GEN-LAST:event_btnSubmitPelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitPelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlInputPelanggan;
    private javax.swing.JTextArea taAlamatPelanggan;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtNoTelponPelanggan;
    // End of variables declaration//GEN-END:variables
}
